# Generated by Django 3.2.4 on 2021-12-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211210_1240'),
        ('users', '0002_auto_20211210_1800'),
    ]

    operations = [
    ]
